import { useState } from 'react'
import { createPortal } from 'react-dom'
import { api } from '../../services/api'
import '../../styles/DeleteAccountModal.css'
import { PasswordVisibilityIcon } from './InterfaceIcons'

export default function DeleteAccountModal({targetId,onClose,onDone}:{targetId?:number;onClose:()=>void;onDone?:()=>void}){
 const [password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await api(targetId?`/usuarios/admin/solicitar-exclusao/${targetId}`:'/usuarios/solicitar-exclusao',{method:'POST',body:JSON.stringify({senha:password})});onDone?.();onClose()}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível agendar a exclusão.')}finally{setSaving(false)}}
 return createPortal(<div className="delete-account-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="delete-account-modal" role="dialog" aria-modal="true" onSubmit={submit}><button className="delete-account-modal__close" type="button" onClick={onClose} aria-label="Fechar">×</button><div className="delete-account-modal__warning" aria-hidden="true">!</div><header><span>ZONA DE PERIGO</span><h2>Excluir conta?</h2><p>Esta ação inicia um período de segurança antes da exclusão definitiva.</p></header><div className="delete-account-modal__notice"><strong>Você terá 7 dias de proteção</strong><p>A conta será desativada agora e apagada definitivamente após 7 dias, evitando exclusões acidentais.</p></div><label>Digite sua senha para confirmar<div><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?'Ocultar senha':'Mostrar senha'}><PasswordVisibilityIcon visible={show}/></button></div></label>{error&&<p className="is-error" role="alert">{error}</p>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="danger" type="submit" disabled={saving}>{saving?'Agendando...':'Excluir conta'}</button></footer></form></div>,document.body)
}
