import { useEffect, useMemo, useState } from 'react'
import AdminIcon from '../../components/admin/AdminIcon'
import AdminSummaryCards from '../../components/admin/AdminSummaryCards'
import CandidateDetailsModal from '../../components/admin/CandidateDetailsModal'
import type { AdminCandidate, CandidateEducation, CandidateExperience, CandidateSkill } from '../../types/AdminCandidate'
import { api } from '../../services/api'
import '../../styles/AdminCandidatesPage.css'
import '../../styles/TalentBankPage.css'

interface Talent {id:number;nome_completo:string;email:string;telefone?:string;cidade?:string;estado?:string;data_nascimento?:string;cargo_desejado?:string;consentimento_talentos:string;possui_candidatura:boolean;apresentacao?:string;motivacao?:string;descricao_valores?:string;arquivo_recomendacao?:string;criado_em?:string;experiencias?:Array<Record<string,unknown>>;formacoes?:Array<Record<string,unknown>>;habilidades?:Array<Record<string,unknown>>;interesses?:string[]}

const PAGE_SIZE=6
const dateFormatter=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'})
const text=(value:unknown,fallback='')=>typeof value==='string'&&value?value:fallback
const number=(value:unknown,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback
const boolean=(value:unknown)=>value===true||value===1||value==='1'
function initials(name:string){const parts=name.trim().split(/\s+/);return `${parts[0]?.[0]??''}${parts.at(-1)?.[0]??''}`.toUpperCase()}
function validDate(value?:string){const parsed=value?new Date(value):new Date(NaN);return Number.isNaN(parsed.getTime())?'Não informado':dateFormatter.format(parsed)}

function mapTalent(item:Talent):AdminCandidate{
 const experiences:CandidateExperience[]=(item.experiencias||[]).map(row=>({company:text(row.empresa,'Não informada'),role:text(row.cargo,'Não informado'),description:text(row.descricao),startDate:text(row.data_inicio),endDate:text(row.data_fim)||undefined,current:boolean(row.atual)}))
 const education:CandidateEducation[]=(item.formacoes||[]).map(row=>({course:text(row.curso,'Não informado'),institution:text(row.instituicao,'Não informada'),currentSemester:number(row.semestre_atual)||undefined,shift:(['manhã','tarde','noite'].includes(text(row.turno))?text(row.turno):'noite') as CandidateEducation['shift'],status:(['cursando','concluido','trancado'].includes(text(row.status))?text(row.status):'cursando') as CandidateEducation['status'],startDate:text(row.data_inicio),endDate:text(row.data_fim)||undefined,certificateUrl:text(row.url_certificado)||undefined}))
 const skills:CandidateSkill[]=(item.habilidades||[]).map(row=>({name:text(row.nome,'Competência'),category:text(row.categoria)==='soft'?'soft':'hard',level:Math.max(1,Math.min(5,number(row.nivel,1))),experienceLevel:(['junior','pleno','senior','especialista'].includes(text(row.nivel_experiencia))?text(row.nivel_experiencia):'junior') as CandidateSkill['experienceLevel']}))
 return{id:item.id,userId:item.id,fullName:item.nome_completo,email:item.email,phone:item.telefone||'Não informado',city:item.cidade||'Não informada',state:item.estado||'',birthDate:item.data_nascimento||'',createdAt:item.criado_em||'',application:{id:item.id,jobId:0,jobTitle:item.cargo_desejado||'Objetivo profissional não informado',area:'Banco de talentos',status:'novo',favorite:false,salaryExpectation:0,availability:'integral',contractPreference:'CLT',workModelPreference:'presencial',createdAt:item.criado_em||new Date().toISOString()},culture:{motivation:item.motivacao||'Não informado.',values:item.descricao_valores||'Não informado.',presentation:item.apresentacao||'Não informado.',recommendationUrl:item.arquivo_recomendacao||undefined},skills,interests:item.interesses||[],education,experiences}
}

export default function TalentBankPage(){
 const[items,setItems]=useState<Talent[]>([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<AdminCandidate|null>(null)
 useEffect(()=>{api<Talent[]>('/usuarios/admin/banco-talentos').then(setItems).catch(reason=>setError(reason instanceof Error?reason.message:'Não foi possível carregar o banco de talentos.'))},[])
 const filtered=useMemo(()=>{const query=search.trim().toLocaleLowerCase('pt-BR');return items.filter(item=>!query||[item.nome_completo,item.email,item.cargo_desejado||'',item.cidade||'',...(item.interesses||[])].some(value=>value.toLocaleLowerCase('pt-BR').includes(query)))},[items,search])
 const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),safePage=Math.min(page,totalPages),visible=filtered.slice((safePage-1)*PAGE_SIZE,safePage*PAGE_SIZE)
 const summary=[{label:'Perfis disponíveis',value:items.length,icon:'users' as const},{label:'Disponíveis sempre',value:items.filter(item=>item.consentimento_talentos==='sempre').length,icon:'check' as const},{label:'Com candidatura',value:items.filter(item=>item.possui_candidatura).length,icon:'clipboard' as const}]
 return <section className="admin-candidates-page talent-bank-page">
  <header className="admin-candidates-header"><div><h1>Banco de talentos</h1><p>Profissionais que autorizaram o uso do perfil em oportunidades atuais e futuras</p></div><span className="admin-candidates-header__count">{filtered.length} {filtered.length===1?'resultado':'resultados'}</span></header>
  <AdminSummaryCards items={summary} ariaLabel="Resumo do banco de talentos"/>
  {error&&<p className="admin-candidates-error" role="alert">{error}</p>}
  <div className="admin-candidates-toolbar talent-bank-toolbar"><label className="admin-candidates-search"><span className="sr-only">Pesquisar no banco de talentos</span><AdminIcon name="search" aria-hidden="true"/><input type="search" value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder="Nome, e-mail, cargo, área ou cidade..."/></label></div>
  <div className="admin-candidates-table"><div className="admin-candidates-table__head talent-bank-table__head" aria-hidden="true"><span>Candidato</span><span>Objetivo profissional</span><span>Entrada</span><span>Autorização</span><span>Ações</span></div><div className="admin-candidates-table__body">{visible.length?visible.map(item=><article className="admin-candidate-row talent-bank-row" key={item.id} onClick={()=>setSelected(mapTalent(item))}><div className="admin-candidate-row__person"><span className="admin-candidate-avatar" aria-hidden="true">{initials(item.nome_completo)}</span><div><strong>{item.nome_completo}</strong><span>{item.email}</span><small>{[item.cidade,item.estado].filter(Boolean).join(' - ')||'Localização não informada'}</small></div></div><div className="admin-candidate-row__job" data-label="Objetivo profissional"><strong>{item.cargo_desejado||'Não informado'}</strong><span>{item.interesses?.slice(0,2).join(' · ')||'Áreas não informadas'}</span></div><div className="admin-candidate-row__date" data-label="Entrada"><strong>{validDate(item.criado_em)}</strong><span>#{String(item.id).padStart(4,'0')}</span></div><div className="talent-bank-consent" data-label="Autorização"><strong>{item.consentimento_talentos==='sempre'?'Banco de talentos':'Com candidatura'}</strong></div><div className="admin-candidate-row__actions"><button type="button" onClick={event=>{event.stopPropagation();setSelected(mapTalent(item))}} aria-label={`Visualizar perfil de ${item.nome_completo}`} title="Visualizar candidato"><AdminIcon name="arrow-right" aria-hidden="true"/></button></div></article>):<div className="admin-candidates-empty"><span aria-hidden="true"><AdminIcon name="search"/></span><strong>Nenhum talento encontrado</strong><p>Tente pesquisar usando outro termo.</p><button type="button" onClick={()=>setSearch('')}>Limpar pesquisa</button></div>}</div></div>
  {filtered.length>PAGE_SIZE&&<nav className="admin-candidates-pagination" aria-label="Paginação do banco de talentos"><span>Página {safePage} de {totalPages}</span><div><button type="button" onClick={()=>setPage(current=>Math.max(1,current-1))} disabled={safePage===1}><AdminIcon name="chevron-down" className="admin-icon--previous"/></button>{Array.from({length:totalPages},(_,index)=>index+1).map(value=><button className={value===safePage?'is-active':''} type="button" onClick={()=>setPage(value)} key={value}>{value}</button>)}<button type="button" onClick={()=>setPage(current=>Math.min(totalPages,current+1))} disabled={safePage===totalPages}><AdminIcon name="chevron-down" className="admin-icon--next"/></button></div></nav>}
  {selected&&<CandidateDetailsModal candidate={selected} onChange={setSelected} onClose={()=>setSelected(null)} talentBankMode/>}
 </section>
}
